// pkg/llm/providers/openai/models.go
package openai

import (
	"github.com/sriramsme/OnlyAgents/pkg/llm"
)

// OpenAIExtensions contains OpenAI-specific capabilities
type OpenAIExtensions struct{}

// ModelRegistry maps model names to their capabilities
var ModelRegistry = map[string]llm.ModelCapabilities{
	"gpt-5-nano": {
		Available:               true,
		Provider:                llm.ProviderOpenAI,
		MaxTokens:               128000,
		DefaultMaxTokens:        64000,
		ContextWindow:           400000,
		SupportsTemperature:     false,
		MinTemperature:          0.0,
		MaxTemperature:          2.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          0.05,
		OutputCostPer1M:         0.40,
		Description:             "Fastest, most cost-efficient version of GPT-5",
		ReleaseDate:             "2024-05",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
		Extensions:              OpenAIExtensions{},
	},

	"gpt-5-mini": {
		Available:               true,
		Provider:                llm.ProviderOpenAI,
		MaxTokens:               128000,
		DefaultMaxTokens:        64000,
		ContextWindow:           400000,
		SupportsTemperature:     false,
		MinTemperature:          0.0,
		MaxTemperature:          2.0,
		DefaultTemperature:      1,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          0.25,
		OutputCostPer1M:         2.00,
		Description:             "Faster, cost-efficient GPT-5 variant for well-defined tasks",
		ReleaseDate:             "2024-05",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
		Extensions:              OpenAIExtensions{},
	},

	"gpt-5.2": {
		Available:               true,
		Provider:                llm.ProviderOpenAI,
		MaxTokens:               128000,
		DefaultMaxTokens:        64000,
		ContextWindow:           400000,
		SupportsTemperature:     false,
		MinTemperature:          0.0,
		MaxTemperature:          2.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          1.75,
		OutputCostPer1M:         14.00,
		Description:             "Best model for coding and agentic tasks across industries",
		ReleaseDate:             "2025-08",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
		Extensions:              OpenAIExtensions{},
	},

	"gpt-5.2-chat": {
		Available:               true,
		Provider:                llm.ProviderOpenAI,
		MaxTokens:               16384,
		DefaultMaxTokens:        8192,
		ContextWindow:           128000,
		SupportsTemperature:     false,
		MinTemperature:          0.0,
		MaxTemperature:          2.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          1.75,
		OutputCostPer1M:         14.00,
		Description:             "GPT-5.2 model optimized for conversational workloads",
		ReleaseDate:             "2025-08",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
		Extensions:              OpenAIExtensions{},
	},

	"gpt-5.2-codex": {
		Available:               true,
		Provider:                llm.ProviderOpenAI,
		MaxTokens:               128000,
		DefaultMaxTokens:        64000,
		ContextWindow:           400000,
		SupportsTemperature:     false,
		MinTemperature:          0.0,
		MaxTemperature:          2.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          1.75,
		OutputCostPer1M:         14.00,
		Description:             "Long-horizon agentic coding model optimized for complex software tasks",
		ReleaseDate:             "2025-08",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
		Extensions:              OpenAIExtensions{},
	},

	"gpt-5.2-pro": {
		Available:               true,
		Provider:                llm.ProviderOpenAI,
		MaxTokens:               128000,
		DefaultMaxTokens:        64000,
		ContextWindow:           400000,
		SupportsTemperature:     false,
		MinTemperature:          0.0,
		MaxTemperature:          2.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          21.00,
		OutputCostPer1M:         168.00,
		Description:             "Higher-precision GPT-5.2 variant with stronger reasoning depth",
		ReleaseDate:             "2025-08",
		Deprecated:              false,
		SupportsPromptCaching:   false,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
		Extensions:              OpenAIExtensions{},
	},

	"gpt-5.1-codex": {
		Available:               true,
		Provider:                llm.ProviderOpenAI,
		MaxTokens:               128000,
		DefaultMaxTokens:        64000,
		ContextWindow:           400000,
		SupportsTemperature:     false,
		MinTemperature:          0.0,
		MaxTemperature:          2.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          1.25,
		OutputCostPer1M:         10.00,
		Description:             "GPT-5.1 Codex optimized for long-horizon agentic coding workflows",
		ReleaseDate:             "2024-09",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
		Extensions:              OpenAIExtensions{},
	},

	"gpt-5.1": {
		Available:               true,
		Provider:                llm.ProviderOpenAI,
		MaxTokens:               128000,
		DefaultMaxTokens:        64000,
		ContextWindow:           400000,
		SupportsTemperature:     false,
		MinTemperature:          0.0,
		MaxTemperature:          2.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          1.25,
		OutputCostPer1M:         10.00,
		Description:             "Advanced GPT-5.1 model for coding and agentic tasks with configurable reasoning effort",
		ReleaseDate:             "2024-09",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
		Extensions:              OpenAIExtensions{},
	},
}
