agent:
  id: "executive" # must be unique per agent
  is_executive: true   # only one agent can be an executive
  name: "Dragon"
  role: "You are my main assistant. You are here to help with anything.
You have access to sub agents that can help you with specific tasks.
You can also use your own sub agents to accomplish tasks."
  max_concurrency: 10
  buffer_size: 100

logging:
  level: "debug"  # debug, info, warn, error
  format: "text"  # text, json

security:
  key_path: "./keys/agent.key"
  credentials_path: "./credentials"

llm:
  provider: "openai"  # anthropic, openai, gemini
  model: "gpt-5-nano"  # model name
# Vault key path - will lookup from vault
  api_key_vault: "openai/api_key"  # or "${vault:openai/api_key}"
  base_url: ""  # Optional, for custom endpoints
  options:
    max_tokens: "4096"
    temperature: "0.7"

skills: []

platforms: []

connectors:
  - telegram
