version: '2'

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - gocyclo
    - misspell

  settings:
    gocyclo:
      min-complexity: 15

    errcheck:
      check-blank: true

    govet:
      # check-shadowing: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  go: '1.25'
