// pkg/llm/providers/anthropic/models.go
package anthropic

import (
	"github.com/sriramsme/OnlyAgents/pkg/llm"
)

// ModelRegistry maps model names to their capabilities
var ModelRegistry = map[string]llm.ModelCapabilities{
	"claude-opus-4.6": { // Alias
		Available:               true,
		Provider:                llm.ProviderAnthropic,
		MaxTokens:               128000,
		DefaultMaxTokens:        4096,
		ContextWindow:           200000,
		SupportsTemperature:     true,
		MinTemperature:          0.0,
		MaxTemperature:          1.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          5.00,
		OutputCostPer1M:         25.00,
		Description:             "The most intelligent model for building agents and coding",
		ReleaseDate:             "2025-05",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
	},
	"claude-opus-4-5": {
		Available:               true,
		Provider:                llm.ProviderAnthropic,
		MaxTokens:               128000,
		DefaultMaxTokens:        4096,
		ContextWindow:           200000,
		SupportsTemperature:     true,
		MinTemperature:          0.0,
		MaxTemperature:          1.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          5.00,
		OutputCostPer1M:         25.00,
		Description:             "Previous generation Opus model",
		ReleaseDate:             "2024-11",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
	},
	"claude-sonnet-4.6": { // Alias
		Available:               true,
		Provider:                llm.ProviderAnthropic,
		MaxTokens:               64000,
		DefaultMaxTokens:        4096,
		ContextWindow:           200000,
		SupportsTemperature:     true,
		MinTemperature:          0.0,
		MaxTemperature:          1.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          3.00,
		OutputCostPer1M:         15.00,
		Description:             "The best combination of speed and intelligence",
		ReleaseDate:             "2025-09",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
	},
	"claude-sonnet-4-5": {
		Available:               true,
		Provider:                llm.ProviderAnthropic,
		MaxTokens:               64000,
		DefaultMaxTokens:        4096,
		ContextWindow:           200000,
		SupportsTemperature:     true,
		MinTemperature:          0.0,
		MaxTemperature:          1.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          3.00,
		OutputCostPer1M:         15.00,
		Description:             "Previous generation Sonnet model",
		ReleaseDate:             "2024-09",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        true,
		SupportsFunctionCalling: true,
	},
	"claude-haiku-4.5": { // Alias
		Available:               true,
		Provider:                llm.ProviderAnthropic,
		MaxTokens:               64000,
		DefaultMaxTokens:        4096,
		ContextWindow:           200000,
		SupportsTemperature:     true,
		MinTemperature:          0.0,
		MaxTemperature:          1.0,
		DefaultTemperature:      1.0,
		SupportsStreaming:       true,
		SupportsToolCalling:     true,
		SupportsVision:          true,
		SupportsJSON:            true,
		InputCostPer1M:          1.00,
		OutputCostPer1M:         5.00,
		Description:             "The fastest model with near-frontier intelligence",
		ReleaseDate:             "2024-10",
		Deprecated:              false,
		SupportsPromptCaching:   true,
		SupportsAudio:           false,
		SupportsReasoningEffort: true,
		IsReasoningModel:        false,
		SupportsFunctionCalling: true,
	},
}

// Cache pricing information (for reference/documentation)
// This could be used for cost estimation features later
var CachePricing = map[string]struct {
	CacheWrite5m float64 // 5 minute TTL
	CacheWrite1h float64 // 1 hour TTL
	CacheHitCost float64 // Cache hits and refreshes
}{
	"claude-opus-4.6": {
		CacheWrite5m: 6.25,
		CacheWrite1h: 10.00,
		CacheHitCost: 0.50,
	},
	"claude-opus-4.5": {
		CacheWrite5m: 6.25,
		CacheWrite1h: 10.00,
		CacheHitCost: 0.50,
	},
	"claude-sonnet-4.6": {
		CacheWrite5m: 3.75,
		CacheWrite1h: 6.00,
		CacheHitCost: 0.30,
	},
	"claude-sonnet-4.5": {
		CacheWrite5m: 3.75,
		CacheWrite1h: 6.00,
		CacheHitCost: 0.30,
	},
	"claude-haiku-4.5": {
		CacheWrite5m: 1.25,
		CacheWrite1h: 2.00,
		CacheHitCost: 0.10,
	},
}
